---
name: Build the Ansible Docker Image

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test building image.
        run: docker build -t mak1806/ansible:1 .
      - name: Run the built image.
        run: docker run -itd --name ansible mak1806/ansible:1
      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty ansible ansible --version
        
  release:
    name: Release to Hub Docker
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mak1806/ansible:1
